### ISSUE TITLE
Nefunkční platební brána

### ISSUE THREAD

**Issue by PPL-PetrSenkerik** [csob/platebnibrana#10]
Dobrý den,
máme problém s použitím testovacích karet
https://github.com/csob/paymentgateway/wiki/Test-cards-and-credentials
na stránkách PPL balíku pro Tebe:
produkční url:
[Etiketa On-line (ppl.cz)](https://www1.ppl.cz/balikprotebe/)
testovací url, 
[Etiketa On-line (ppl.cz)](https://www1.rc1.ppl.cz/balikprotebe/)
nedostupné mimo DHL prostředí.

https://iplatebnibrana.csob.cz/pay/ppl.cz/9642a590-626a-42cd-90f2-04da0a5f736e/

ID: M1MIPS3947

Prosím o řešení.

Děkuji Petr Šenkeřík

**Comment by jgrmelova** [comment]
Dobrý den, 

Váš požadavek prověřujeme o výsledku Vás budu informovat. 

Hezký den. 

--
Jana Grmelová 
IT administrátor

**Comment by PPL-PetrSenkerik** [comment]
Dobrý den,

prosím o update stavu.

Děkuji, Petr Šenkeřík

**Comment by jgrmelova** [comment]
Dobrý den, 

platební brána by již měla být plně funkční. Důvodem byla chyba hardware na integračním prostředí a následné nekorektní naběhnutí aplikace pro autentikaci.

Prosím Vás o otestování na Vaší straně a informaci, zda je již vše v pořádku.

Děkuji.

--- 
Jana Grmelová

**Comment by jgrmelova** [comment]
Dobrý den, 

na tento požadavek neevidujeme v současné chvíli žádnou reakci. Požadavek ukončuji. V případě potřeby je možné požadavek znovu otevřít nebo zadat nový. 

Hezký den. 

--- 
Jana Grmelová
