### ISSUE TITLE
Nový terminál nepřijímá stravenkové karty 

### ISSUE THREAD

**Issue by KhangLek** [csob/platebnibrana#12]
Dobrý den, 

Náš nový terminál nepřijímá stravenkovou kartu i když máme smlouvy s partnery a ten starý terminál přijímal normálně.

Prosím můžete mi poradit ?

Děkuji

KL

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek ohledně platebního terminálu směrujte na linku 495 800 116 klapka 1 případně akceptacekaret@csob.cz. 
s pozdravem
Milan Spisar
