### ISSUE TITLE
Částka tokenizačni (úvodní) platby?

### ISSUE THREAD

**Issue by obud** [csob/platebnibrana#13]
Dobrý den,

potřebujeme-li tokenizovat kartu (OneClick), dočetl jsem se, že pro úspěšný průběh je nutné založit iniciální transakci v částce minimálně 1 jednotky měny.

Nicméně, jak to řešit, pokud potřebujeme kartu pouze tokenizovat bez toho, aby se zákazníkovi platba v konečném důsledku strhla z účtu?

Protože například u CZK to takový problém není, jedná-li se o 1 Kč, což není moc. Ovšem máme-li bránu v EUR, 1 EURO je už mnohem větší částka... Standardně se dělají úvodní transakce 1 centové.

Je tedy možné úvodní transakci refundovat? Je možné už před zaúčtováním, nebo až po zaúčtování? Jak je to s poplatky (a fixními poplatky za transakce)?

Děkuji.

**Comment by Mspisar** [comment]
Dobrý den,

požadavek jsme zaevidovali a předali k řešení. 

s pozdravem

Milan Spisar
1st level support 
Monet+

**Comment by dmarek** [comment]
Dobrý den,

co se týče EUR, minimální částka, kterou je možné autorizovat a která projde zůčtováním je 10 centů. Pokud transakce projde zůčtováním, je možné ji pak refundovat.

**Comment by obud** [comment]
Dobrý den,

u CZK je to tedy 1 Kč? Nebo stačí jeden haléř?

Jak je to prosím s poplatky na refundaci?

Děkuji.

**Comment by dmarek** [comment]
Dobrý den, 

pro CZK je to 40 haléřů. Ze strany ČSOB (acquirera) nejsou učtovány žádné poplatky za provedení refundu.

**Comment by obud** [comment]
Dobrý den,

v případě refundu jsou vráceny i poplatky z transakce? (Tzn. % + 0,5 CZK u baličku je u Start?)

**Comment by jgrmelova** [comment]
Dobrý den, 

pro detailnější informace ohledně poplatků doporučuji obrátit se přímo na Vašeho obchodního zástupce. 

V případě doplňujících technických dotazů, jsme Vám plně k dispozici. 

Hezký den. 

--- 
Jana Grmelová
