### ISSUE TITLE
Testování OneClick plateb na integračním prostředí

### ISSUE THREAD

**Issue by jardadu** [csob/platebnibrana#14]
Dobrý den,

snažím se otestovat potvrzení platby v rámci jejího ověření, ale i když postupuju podle instrukcí na https://github.com/csob/platebnibrana/wiki/Testovac%C3%AD-karty - úvodní OneClick platba placena kartou 4000007000030004 s CVC 100, tak v případě vytvoření následné OneClick platby s jinou částkou než 100 a 200 při volání oneclick/process nedostávám zpět objekt actions s adresou pro otevření ověřovací stránky, ale pouze tyto údaje:

{
	"payId":"0c30d8524d3f@HH",
	"resultCode":0,
	"resultMessage":"OK",
	"dttm":"20220823093749",
	"signature":"...",
	"paymentStatus":2
}

Můžete prosím ověřit, proč mi není vrácena adresa pro potvrzení platby? 

Děkuji (obchodník M1MIPS7116)

**Comment by jgrmelova** [comment]
Dobrý den,

požadavek jsme zaevidovali a předali k prověření. 
O výsledku Vás budeme informovat. 

Hezký den. 

--- 
Jana Grmelová

**Comment by jgrmelova** [comment]
Dobrý den, 

výsledek ověření a následné autorizace je potřeba zjistit následným voláním payment/status. Doba zpracování se může lišit v závislosti na tom, zda je vyžadováno potvrzení platby v rámci jejího ověření:

- pokud potvrzení není vyžadováno, je doporučená doba volání je 2-3 vteřiny po volání oneclick/process, pokud je stav platby stále 2 (platba probíhá), doporučujeme periodicky volat v intervalu 5 vteřin (celková doba autorizace závisí na zpracování požadavku v systémech VISA/MC a může být v nejhorším případě až 60 vteřin).
- pokud je potvrzení vyžadováno, může trvat řádově minuty, než je zákazníkem platba potvrzena a vydavatel karty dokončí ověření. V tomto případě doporučujeme volat payment/status periodicky v delším intervalu např. 30 vteřin.

V případě doplňujících dotazů jsme Vám k dispozici. 

Hezký den. 

--- 
Jana Grmelová

**Comment by jardadu** [comment]
Dobrý den,

děkuji za upozornění, pokud tedy adresa pro ověření platby není v odpovědi volání metody oneclick/process, může se objevit při následném opakovaném volání payment/status a v takovém případě prodlužuji interval volání a otevírám adresu browserChallenge v předaném objektu actions.

Přeji pěkný den
