### ISSUE TITLE
Špatný den ve Wiki

### ISSUE THREAD

**Issue by JiriKr** [csob/platebnibrana#15]
Dobrý den,

ve [wiki s popisem výměny certifikátu](https://github.com/csob/platebnibrana/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy#v%C3%BDm%C4%9Bna-certifik%C3%A1tu-httpsapiplatebnibranacsobcz) je uvedeno (na více místech)
> ... pondělí 4. září 2022

ale dle kalendáře je 4. září neděle. Dle platnosti cetrifikátu by tedy zde mělo být spíše "**neděle** 4. září 2022".

**Comment by jgrmelova** [comment]
Dobrý den, 

děkujeme za upozornění. Konec platnosti serverového certifikátu je **v neděli 04.09.2022**. Informaci jsem na stránkách upravila. 

Hezký den.

---
Jana Grmelová
