### ISSUE TITLE
Problém s oneclick/init bez přítomnosti zákazníka (clientInitiated = false)

### ISSUE THREAD

**Issue by jardadu** [csob/platebnibrana#16]
Dobrý den,

v případě testování oneclick/init bez přítomnosti zákazníka (clientInitiated = false), mi v odpovědi přijde místo objektu OneclickInitResponse html kód s textem "The requested URL was rejected. Please consult with your administrator. Your support ID is: 2732842130127883404". Předchozí volání oneclick/echo ("origPayId":"c751f7c02bdd@HH","merchantId":"M1MIPS7116","dttm":"20220902073914") proběhne v pořádku. Můžete mě prosím navést, kde by mohla být chyba, v dokumentaci jsem takový případ nenašel.

Děkuji

**Comment by mschre400** [comment]
Dobrý den,
Váš požadavek byl zaevidován pod: TSGSMIPS-17766 a předán k řešení. O dalším průběhu Vás budeme informovat.
S přáním hezkého dne

**Comment by jgrmelova** [comment]
Dobrý den, 

při prověření jsme zjistili, že v rámci inicializace zasíláte parametr clientIp ovšem v nesprávném formátu. ("clientIp":""). V případě nastavení parametru clientInitiated = false není parametr clientIP povinný. Pokud je ale tento parametr zaslán, musí být ve správném formátu jako v případě clientInitiated = true (nebo null). 

V případě doplňujících dotazů jsme Vám k dispozici.

Hezký den. 

---
Jana Grmelová

**Comment by jardadu** [comment]
Děkuji za prověření, kód jsem upravil a oneclick platba bez přítomnosti zákazníka funguje. Omlouvám se, zmátla mě ta divná chyba.

**Comment by janbrasna** [comment]
@jardadu Ta divna chyba je bohuzel znamy problem: https://github.com/csob/paymentgateway/issues/605#issuecomment-976184198 — pri nekterych chybach se do toho proste vlozi nadrazeny server a vraceny payload je pak takovy jaky je… :(

@jgrmelova Pokud se parametr nepouziva, bylo by aspon trosku mozne ho proste nevalidovat, resp. validaci nezpusobovat podobny fatalni stav, a jen ho potichu ignorovat? Usetrily by se podobne incidenty s odpovedmi z F5…
