### ISSUE TITLE
Žádost o stažení "3ds-method-notification" na iOS

### ISSUE THREAD

**Issue by janlanger** [csob/platebnibrana#18]
Dobrý den,

na ibráně jsme narazili na podivnou žádost o stažení souboru při ověřování fingerprintu na iOS/iPadOS zařízeních. Děje se to u apple pay, oneclick a dokonce to vyskakuje i při zadávání čísla karty přímo na ibráně. 

![file](https://user-images.githubusercontent.com/415695/191530835-19425f88-6b8c-43b3-af04-6783a0dbdafe.jpg)

Na Androidu ani Windows k ničemu takovému nedochází.

MID M1E3CB0860 ale na tom to asi závislé nebude.

Potřebovali bychom primárně vědět jestli je to problém jen testovacího prostředí, nebo se to děje i v produkci...

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by vzikmund** [comment]
Dobrý den, narážím na stejný problém. Avšak u mě dochází k přesměrování na adresu `https://iplatebnibrana.csob.cz/pay/3ds-method-notification` a tam je mi nabídnut ke stažení soubor `3ds-method-notification` o velikosti 0 kB.

**Comment by mrazekl** [comment]
Dobrý den,
v produkčním prostředí se tento problém nevyskytoval. Příčinou bylo chybné nastavení rozsahu pro testovací karty, konkrétně parametr pro 3ds metodu. V produkčním prostředí je tento parametr poskytován automaticky z directory serveru, kdežto na testu musí být zadán manuálně a přitom došlo k pochybení.
Nyní je již opraveno, vyzkoušejte prosím.

**Comment by mrazekl** [comment]
@vzikmund  - mělo by to řešit i váš problém, v případě že ne, dejte prosím vědět.

**Comment by vzikmund** [comment]
@mrazekl Dobrý den, potvrzuji, že nyní se platba zpracuje správně. Děkuji!

**Comment by MysticCajda** [comment]
Dobrý den,

u mě problém bohuže stále přetrvává i v produkčním prostředí viz. #17 

mohu poprosit o radu? děkuji

![obrazek](https://user-images.githubusercontent.com/39945788/193546261-b133038a-feab-4bd1-bbef-6e73124944ba.png)

**Comment by vzikmund** [comment]
@mrazekl Po notifikaci s komentářem od @MysticCajda jsem vyzkoušel Apple Pay znovu v testovacím prostředí a znovu jsem přesměrován viz https://github.com/csob/platebnibrana/issues/18#issuecomment-1256915647. Beru tedy zpět, že to funguje :)

No.. ještě, že jsme to zatím nedali do produkce. :)

**Comment by mrazekl** [comment]
@MysticCajda - to byl případ, kdy ani v produkčním prostředí není pro danou kartu 3ds-metoda. Od dnešního rána se v těchto případech nevrací hodnota pro získání 3ds-metody a není tedy co provolávat.
Nicméně vidím že včerejší pokus i dnešní applepay/process končí na chybu podpisu. Řetězec pro podpis by měl mít následující pořadí:
M1MIPS***8|d368*********@HJ|20221004093523|Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1|text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8|cs-CZ|true|3*|3*0|-120|false

**Comment by mrazekl** [comment]
@vzikmund  - bohužel se nám ještě nepodařila odhalit přesná příčina problému na testovacím prostředí. Debug stále probíhá, budu vás informovat.

**Comment by MysticCajda** [comment]
@mrazekl děkuji, už nám to funguje
