### ISSUE TITLE
customer.login - přihlášení přes FB/Google a 2FA

### ISSUE THREAD

**Issue by janlanger** [csob/platebnibrana#2]
Dobrý den,

jaká je správná hodnota nového `customer.login` pokud se uživatel přihlásil přes Facebook nebo Google login?

jaká je správná hodnota pokud účet používá 2 faktorové přihlášení, tedy jméno+heslo+ověření SMS nebo OTP?

**Comment by martinhubik** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Martin Hubík
IT Support Specialist

**Comment by jgrmelova** [comment]
Dobrý den, 

pokud se uživatel přihlásil přes Facebook nebo Google login, tak customer.login doporučujeme vyplnit jako 'thirdparty' nebo 'federated'. 

Co se týče 2 faktorového přihlášení a nejedná se např. o přihlášení pomocí FIDO autentikátoru, tak zde není přímá specifikace (není nutné tuto informaci předávat). 

V případě doplňujících dotazů jsem Vám k dispozici. 

---
Jana Grmelová
IT administrátor
