### ISSUE TITLE
Api po přechodu na verzi 1.9 vrací chybu - 401 Unauthorized -  {"resultCode":110,"resultMessage":"Wrong signature"}

### ISSUE THREAD

**Issue by lukassimecek** [csob/platebnibrana#20]
Dobrý den,
klientovi převádíme api platební brány z verze 1.7 na 1.9 a při testování mi api hlásí chybu "Wrong signature". I přesto, že jsem změnil algoritmus pro podpis z SHA1 na SHA256. Klient má merchantId - M1E3CB1089. Zkusil jsem pro jistotu i testovací prostředí (iapi.iplatebnibrana.csob.cz/api/v1.9/payment/init) s nově vygenerovaným merchantId - A3067fTvYa, ale i zde mi api hlásí stejnou chybu.
Nevěděli by jste prosím, čím by to mohlo být? Zkoušel jsem použít i použití SHA256 z Vaších příkladů, ale se stejným výsledkem. 

Děkuji moc

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

kolem 14. hodiny vidím v logu na produkčním prostředí u Merchant ID M1E3CB1089 informaci:
_Nov 14, 2022 @ 13:59:24.213	Invalid dttm: M1E3CB1089/00010101000000_
_Nov 14, 2022 @ 13:59:24.214	echo failed: httpStatus=400, msg=MipsException: Invalid signature for merchant M1E3CB1089_

U požadavku se vyplňuje aktuální datum a čas odpovídající časové zóně CET / CEST, platební brána kontroluje předávanou hodnotu a toleruje určitou odchylku (řádově v minutách) v porovnání s aktuálním časem synchronizovaným na serverech platební brány. 

Při přechodu na vyšší verzi doporučuji také zkontrolovat, zda jsou v rámci podpisu zasílány všechny parametry a zda jsou ve správném pořadí. (https://github.com/csob/platebnibrana/wiki/Z%C3%A1kladn%C3%AD-metody) Dále zda jsou využívány správné certifikáty pro šifrování a dešifrování a také algoritmus. 

Pro správné nasazení je vhodné nejdříve provést přechod na integračním prostředí a po odladění převést úpravy i na produkční prostředí. 

V případě, že budete potřebovat prověřit další transakce po úpravách, prosím Vás o zaslání čísla transakce (PayID) a přibližného času provedení požadavku. 

Hezký den.

**Comment by janbrasna** [comment]
@lukassimecek Diky za nahlaseni, pro _echo_ operaci dostavate jinou chybovou hlasku nez v cem je skutecny duvod. Problem mate jak pise vyse @jgrmelova — neposilate spravny (platny) dttm timestamp. Na naprave chybove hlasky uz se pracuje.

**Comment by ZyxSoFar** [comment]
Dobrý den,

měl bych dotaz ohledně implementace nové verze platební brány v. 1.9.
V integračním prostředí se snažím odeslat požadavek na testovací bránu, ale stále se nám vrací odpověď 401 {"resultCode":110,"resultMessage":"Wrong signature"}

Jedná se o klienta s merchantid: M1MIPS7386
dttm: 20221130083609

Provedli jsme vyganerování testovacích klíčů na stránce:
https://iplatebnibrana.csob.cz/keygen/

Požadavky odesíláme na testovací bránu:
https://iapi.iplatebnibrana.csob.cz/api/v1.9

Pro ověření používáme stávající veřejný klíč co již používáme v produkčním prostředí u verze 1.7:
mips_platebnibrana.csob.cz.pub

Můžete prosím ve vašem logu ověřit, proč nelze podpis ověřit?
Děkuji.

**Comment by janbrasna** [comment]
@ZyxSoFar Zkontrolujte si zda pouzivate spravny algoritmus pro podpis, do v1.7 to bylo SHA1, od v1.8 je potreba podepisovat SHA256: [CHANGELOG.md#v18-102019](https://github.com/csob/paymentgateway/blob/master/CHANGELOG.md#v18-102019)

**Comment by ZyxSoFar** [comment]
To jsme již také zkoušeli, ale bohužel to stále nefunguje.
```
$privateKeyId = openssl_get_privatekey($private, $this->privateKeyPassword);
openssl_sign($text, $signature, $privateKeyId, OPENSSL_ALGO_SHA256);
$signature = base64_encode($signature);
openssl_free_key($privateKeyId);
```

**Comment by janbrasna** [comment]
@jgrmelova Trackuje nekdo prosim tu opravu odesilane chybove hlasky z validaci… tzn. ze se vraci "Wrong signature" misto "Invalid dttm"?

**Comment by konopi79** [comment]
Dobrý den,
také mám stejný problém s {"resultCode":110,"resultMessage":"Wrong signature"} na integračním prostředí https://iapi.iplatebnibrana.csob.cz/api/v1.9/payment/init, dostávám 401.
MerchantID M1E3CB2863. Vypadá to jako nějakou generickou hlášku, která při debuggingu moc nepomůže.
Klíče vygenerovány, uploadnuty. Payload requestu by měl být také ok.
Můžete prosím prověřit poslední request, nevím, co dělám špatně.
Děkuji.

**Comment by mrottner** [comment]
Dobrý den,
i u nás se objevuje stejná chyba na integračním prostředí - {"resultCode":110,"resultMessage":"Wrong signature"}
MerchantId: A4106kYeNA
Volání metody **echo** proběhne bez problémů, takže v klíčích problém nebude. Vše se podepisuje pomocí SHA256withRSA.
Bylo by prosím možné zkontrolovat naše requesty volání, je-li tam nějaký parametr chybně / chybějící?

Děkuji

**Comment by man088** [comment]
Dobrý den, máme stejný problém {"resultCode":110,"resultMessage":"Wrong signature"}
Přišli jsme na to, že je problém v zasílané částce na bránu. 
Pokud pošleme částku v Kč (máme vše na setiny samozřejmě)
- 1210.60  - dostaneme se při redisrectu na 404 - resultCode 110 - Wrong signature
- 1210.00 - jsme na bráně OK
- 1210.20 - jsme na bráně OK
- 1210.58 - jsme na bráně OK
- 1210.59 - dostaneme se při redisrectu na 404  - resultCode 110 - Wrong signature
- 1210.62 - dostaneme se při redisrectu na 404 - resultCode 110 - Wrong signature
- 10.20 - jsme na bráně OK
- mohl bych pokračovat dále... např další částka co neprojde je 
- 1211.60 dostaneme se při redisrectu na 404  - resultCode 110 - Wrong signature

Můžete mi vysvětlit, jak může mít na toto částka vliv? 
Merchant ID 
M1MIPS4638
Děkuji

**Comment by jgrmelova** [comment]
Dobrý den, 

za posledních 30 dní na testovacím ani integračním prostředí) nevidím žádné transakce pro Merchant ID M1MIPS4638. Prosím Vás o zaslání payID daných transakcí (číslo objednávky nebo VS). Také prosím o zaslání celého požadavku včetně dat, přesného času zaslání a také řetězce pro podpis (alespoň dvou uvedených transakcí) . Údaje můžete zaslat na e-mail servis@monetplus.cz.  Situaci prověříme.

Děkuji
