### ISSUE TITLE
Testovací karty výsledek ověření dle placené částky přestal fungovat OneClick

### ISSUE THREAD

**Issue by MMirekk** [csob/platebnibrana#23]
Dobrý den,
integruji novou verzi platební brány 1.9 a ještě minulý týden mi fungovalo, že jsem si výsledek ověření platby mohl ověřit podle částky 100 - úspěšné, 200- neúspěšné, jiná částka výzva k zadání OTP kódu.
Dnes mě to při jakékoliv částce i 100 i 200 vyzívá k zadání OTP kódu a potom projdou i ta za 200?
Kde se stala chyba?
Díky

**Comment by matejcekdav** [comment]
Dobrý den, hodnota 100 a 200 znamená 1 Kč a 2 Kč. Zkuste posílat na tyto částky / hodnoty a mělo by se to chovat dle dokumentace. Dejte vědět. Děkuji, David M.

**Comment by MMirekk** [comment]
Ano je to tak, před chvilkou jsme na to přišli při tom jak jsme spolu telefonovali. Díky upravím si a myslím, že je možné tuto issue uzavřít. :)
