### ISSUE TITLE
platební brána od ČSOB na Shoptet

### ISSUE THREAD

**Issue by germanb95** [csob/platebnibrana#27]
Dobrý den,
Chtěl bych zapojit platební bránu od ČSOB na Shoptet. Jde to udělat, pokud nejsem programator?

děkuji a přeji pěkný den

**Comment by mjanek** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
Miroslav Janek

**Comment by jgrmelova** [comment]
Dobrý den, 

v případě, že nemáte k dispozici programátora, který by implementaci platební brány provedl za Vás, doporučuji obrátit se přímo na Shoptet se žádostí o napojení platební brány, u které nebude implementace programátorem nutná.  

Hezký den. 

---
Jana Grmelová
