### ISSUE TITLE
API 1.9 - 3DS SDK

### ISSUE THREAD

**Issue by IgorSvoboda** [csob/platebnibrana#30]
Dobry den, chystame sa integrovat platbu cez API 1.9 do nativnej Android apky. V dokumentacii sa spomina (https://github.com/csob/platebnibrana/wiki/Metody-pro-OneClick-platbu#fingerprintsdk-data-), ze je potrebne pouzit 3DS SDK. 
Chcem sa opytat, kde mozme dane SDK ziskat.
Vdaka

**Comment by martinhubik-mp** [comment]
Dobrý den,
Váš požadavek byl zaevidován pod: KBC-3024 a předán k řešení.
O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Martin Hubík
1st level support
M +420 603 197 054
E [servis@monetplus.cz](mailto:servis@monetplus.cz)
MONET+,a.s., Za Dvorem 505, 763 14 Zlín-Štípa

**Comment by matejcekdav** [comment]
Dobrý den, 3DS SDK není vázané na platební bránu a můžete tak použít jakékoli SDK s EMV certifikací. Seznam jejich poskytovatelů najdete zde - https://www.emvco.com/approved-registered/approved-products/?action=search_products&px_search=&emvco_product_3dsecure%5B%5D=3ds-sdk-products. 
3DS SDK si tedy můžete zařídit po své ose, případně ČSOB pracuje a nakupuje SDK licence od společnosti NetCetera – budete-li o něj mít zájem, kontaktujte, prosím, svého obchodního zástupce.
