### ISSUE TITLE
implementacni vs produkcni volani

### ISSUE THREAD

**Issue by hanusr** [csob/platebnibrana#32]
Dobry den, 
prosim o info, jestli je neco potrebne zmenit pri volani s produkcnim setupem. Testovaci volani funguje OK. 
Po zmene setupu na produkcni (2x adresa, 2x klic) se v Response nenachazi Result a mame jenom hlasku : 
An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
![image](https://user-images.githubusercontent.com/125982221/220350164-453d5642-ce71-4f47-b5eb-c543ab840875.png)

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

můžete mi, prosím, zaslat Merchant ID a případně čas pokusu? Prověřím logy. 

Děkuji.

**Comment by hanusr** [comment]
Dobry den,
Ista komunikace prebehla medzi CSOB pan Jan Fousek a dalšími ludmi a zakaznikom (Air Navigation Services) ale bolo to cez x ludi. Ja som bol v kopiach tych mailov a doteraz zo strany CSOB ste zaznamenali pokusy len na implementacnu branu ale na PROD nie.
Potreboval by som tu komunikaciu zjednodusit, tak som skusil takyto kanal.

Merchant ID  : M1EPAY0342
Testy napr. 20.2. cca 10:00

S pozdravem | Best Regards

Radomír Hanus

Solution Developer

[Konica Minolta logo]


Konica Minolta IT Solutions Czech a.s.
U Plynárny 1002/97, 10100 Praha 10


Mobil:

+420 731 600 422

Email:

***@***.******@***.***>

Web:

www.konicaminoltaits.cz<http://www.konicaminoltaits.cz/>





[Giving Shape to Ideas]

**Comment by hanusr** [comment]
Dobry den, podarilo sa dopatrat chybicku v setupe. Dakujem pekne za kvalitnu podporu.

**Comment by jgrmelova** [comment]
Vyřešeno prostřednictvím e-mailu.
