### ISSUE TITLE
OneClick - status timeOut

### ISSUE THREAD

**Issue by tosnerDavid** [csob/platebnibrana#35]
Dobrý den,
máme na testovacím prostředí zprovozněné platby přes OneClick a potřebujeme ošetřit okrajový případ, který však může nastat.

Popis situace:
- odešlu request oneclick/init
-- obržím OK response
- odešlu request oneclick/process s payId dle oneclick/init
-- obržím OK response
- po dobu 15sec periodicky odesílám payment/status s daným PayId
-- pokud se mi vrátí paymentStatus=(3, 5, 6)
---- tak vrátím uživateli info o tom že platba byla ODMÍTNUTA
-- pokud se mi vrátí paymentStatus=(4, 7, 8), 
---- tak vrátím uživateli info o tom že platba byla POTVRZENA
-- pokud se mi vrátí status_response["actions"]["authenticate"]["browserChallenge"]["url"]
---- tak uživatele přesměruji na dodané URL pro dodatečnou verifikaci

Otázkou je co by mělo být standardní chování v případě, že nedostaneme od platební brány během 15sec ani jednu z těchto odpovědí? Případně jestli tento problém vůbec může v reálném provozu nastat.
- platba je v tomto případě stále v procesu tj. paymentStatus==2

Děkuji

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

payment/status by měl být volán do doby než obdržíte v rámci něj actions pro další průběh platby nebo jeden z konečných stavů transakce (úspěšný / neúspěšný). 

V případě, že jsou zaslány actions, je časový limit na provedení 30 sekund. Pokud k provolání nedojde, je transakce zamítnuta na základě vypršení časového limitu. Stav se tedy změní na 6. Pokud není ověření vyžadováno, je transakce schválená a její stav ze změní na 4 / 7. 

V případě doplňujících dotazů jsem Vám k dispozici. 

Hezký den.
