### ISSUE TITLE
Vyžadování 3DS pro konkrétní platby

### ISSUE THREAD

**Issue by OndrejSykora** [csob/platebnibrana#37]
Zdravím, měl bych asi spíš dotaz na funkcionalitu. Od klienta jsme dostali požadavek na zjištění, zdali by šlo u některých plateb vyžadovat 3DS ověření ze strany obchodu?

Jde primárně o farudy v případě, kdy například dochází k nákupu elektronických licencí pomocí odcizené platební karty.

Klient by tak chtěl vědět, jestli je možné, třeba právě pro nákupy digitálních produktů, 3DS po platební bráně vyžadovat?

Vím, že pomocí [dodatečných dat o nákupu](https://github.com/csob/platebnibrana/wiki/Dodatečná-data-o-nákupu) jde například specifikovat způsob a rychlost doručení, jestli se jedná o elektronické nebo fyzické produkty, ale nevím jestli se na základě toho dá vyžadovat důkladnější ověření platby, nebo si toto řeší platební brána sama bez možnosti tuto skutečnost nějak ovlivnit.

Předem děkuji za odpověď, Sýkora.

**Comment by matejcekdav** [comment]
Dobrý den, 

bohužel toto z naší strany možné není. Jediná situace, kdy vyžadujeme směrem k vydavateli karty challenge v 3DS, je vytvoření šablony pro následné OneClick platby. Silné ověření je podmínka právě pro uložení karty pro platby na klik.

Jinak v ostatních případech u platby kartou, jestli bude požadavek transakci silně ověřit v rámci 3DS nebo zdali projde transakce bez silného ověření klientem, o tom rozhoduje obecně vydavatel karty. 

David M.

**Comment by OndrejSykora** [comment]
Děkuji za odpověď.

**Comment by matejcekdav** [comment]
Není zač. Ještě bych možná doplnil, že defacto všechny běžné platby kartou jsou posílané do 3DS a silně ověřené. Záleží však jakým modelem, zdali je ověří vydavatel karty na své straně pomocí svých rizikových modelů a pustí transakci bez dodatečného ověření klienta (tzv. frictionless cesta), nebo zdali si vyžádá právě to dodatečné ověření klienta. Tak či tak ale je transakce brána jako silně ověřená, tudíž odpovědnost za případnou reklamaci jde za vydavatelem karty. Existují určité výjimky, kdy transakce do 3DS posílané nejsou, jako je v našem případě například Platba na klik formou MIT (merchant initiated transakce), nebo podlimitní transakce, tzv. LVP.  David M.
