### ISSUE TITLE
Automaticke vyplnovani na iPhonu

### ISSUE THREAD

**Issue by viktorhanacek** [csob/platebnibrana#39]
Mohli byste prosim odladit branu pro plnou kompatibilitu s automatickym vyplnovanim karet na iPhonu (auto-fill)?

Jsem zakaznik a uprimne se vzdycky zhrozim, kdyz uvidim CSOB branu, pritom staci jen zlehka odladit kod.

Problem totiz je, ze brana nedovoli iPhonu vlozit platnost karty a posledni cislovka vzdy ve formulari chybi a musim ji dopsat rucne. Tzn. v iPhonu vidim, ze chce vyplnit 07/24, ale do formulare se propise pouze 07/2 proto, ze (asi) skript nedovoli vic znaku.

**Comment by FVarak** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by viktorhanacek** [comment]
iPhone 14 Pro, Safari prohlížeč a standardní Apple Keychain. Problém mám dlouhodobě roky, takže to asi nemá souvislost s verzí čehokoliv.

**Comment by janbrasna** [comment]
Mozna souvislost je s jazykem (locale) toho zarizeni. Vypada to, ze pro cesky nastaveny system vyplnuje Safari autofill hodnotu "24" (YY), kdezto anglicky system i pres ceske datove formaty posila hodnotu "2024" (YYYY) a ta se pak urizne a neprojde validaci.

**Comment by viktorhanacek** [comment]
Nevím, každopádně to už funguje jak má 👍🏻
