### ISSUE TITLE
v1.9 payment/init mezera na konci jmena

### ISSUE THREAD

**Issue by comnet-s-r-o** [csob/platebnibrana#4]
pokud končí customer.name mezerou, vrátí payment/init chybu 400
v dokumentaci jsem zmínku o formátování jména nenalezl, jen požadavek na max. délku 45 znaků

**Comment by martinhubik-mp** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Martin Hubík
IT Support Specialist

**Comment by jgrmelova** [comment]
Dobrý den, 

situaci jsme prověřili a provedli úpravu. Aktuálně by již mělo být v pořádku. 

V případě dotazů jsem Vám k dispozici. 

Hezký den. 

--
Jana Grmelová
IT administrátor

**Comment by dmarek** [comment]
Dobrý den, předchozí komentář byl vložen omylem, validace na platební bráně zůstává nezměněna, doplnili jsme dokumentaci na stránce "Dodatečná data o nákupu" ([CZ](https://github.com/csob/platebnibrana/wiki/Dodate%C4%8Dn%C3%A1-data-o-n%C3%A1kupu) a [EN](https://github.com/csob/paymentgateway/wiki/Purchase-metadata))
