### ISSUE TITLE
GooglePay - Missing parameter fingerprint.browser

### ISSUE THREAD

**Issue by milanSkrob** [csob/platebnibrana#41]
Dobrý den.
Pokud simuluji GooglePay nákup bez nutnosti provedení otisku prohlížeče (totalAmount = 300, 400, 500), tak u googlePay/init nedostanu v odpovědi objekt actions (to je podle dokumentace v pořádku). 
Poté ale tedy zavolám googlePay/process, kde objekt (položku) fingerprint vůbec nepředám (null). V odpovědi dostanu resultCode 110, a resulMessage: "Missing parameter fingerprint.browser"

Jedná se v testu o payId: 822b2bb6d504@IF

**Comment by FVarak** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

co se týče fingerprintu, tak v případě, že fingerprint vyžaduje issuer, je zaslána actions v rámci požadavku INIT, kde je nutné provolání dané url adresy, co zajistí získaní potřebných údajů i pro 3DS ověření. Pokud však není fingerprint požadován isssuerem, je potřebné aby došlo ze strany obchodníka k zaslání potřebných údajů pro 3DS ověření v rámci požadavku payment/process. (Otisk browseru je tedy nutné provést svépomocí pro získání dat pro naplnění fingerprintu.) Viz dokumentace https://github.com/csob/platebnibrana/wiki/Metody-pro-OneClick-platbu#fingerprint.

V případě doplňujících dotazů, jsme vám k dispozici. 

Hezký den. 

---
Jana Grmelová
