### ISSUE TITLE
Špatná data v rozšíření trxDates

### ISSUE THREAD

**Issue by pvlst** [csob/platebnibrana#42]
Rozšíření **trxDates**, které má vracet dodatečné datumy k platbě kartou, vrací čas v nesprávné časové zóně.

Příklad:
- nákup uskutečněn via Google Pay na integračním prostředí 21. 6. 2023 ve **23:29 lokálního času** (CEST)
- `CreatedDate` ale obsahuje `"2023-06-21T23:29:07.670Z"`, což znamená **2023-06-22T01:29:07.670 lokálního času**
- `AuthDate` také obsahuje `"230621232922"`, což je stejný případ

Můžete to, prosím, opravit?

Dále by bylo vhodné srovnat formáty těchto datumů do konzistentní podoby, momentálně je každý ze 3 vracených (CreatedDate, AuthDate, SettlementDate) v jiném formátu.

V neposlední řadě nám ze status endpointu chodí i extension `trxDetail`, nikde jsem nenašel její popis. O co se jedná?

**Comment by mjanek** [comment]
Dobrýden,
Váš požadavekbyl zaevidován a předán k řešení. O dalším průběhu Vás budeinformovat odpovědný servisní technik.
Miroslav Janek

**Comment by georgievaja** [comment]
Dobrý den, @mjanek je zde nějaký posun? Extension `trxDates` není kvůli těmto problémům plně použitelná.

**Comment by jgrmelova** [comment]
Dobrý den, 

sjednocení formátu všech datumů do konzistentní podoby není možné, jednalo by se o úpravu API, která by ovlivnila všechny již naimplementové platební brány. Je však připravena úprava formátování v extension Trxdates. Tato úprava nyní čeká na otestování. 

O nasazení úpravy do produčkního prostředí Vás budeme informovat. 

Co se týče trxDetail jedná se o informace o transakci, zda se jednalo o platbu nebo oneclick a kolik pokusů bylo provedeno. 

Hezký den. 

---
Jana Grmelová
IT administrátor

**Comment by jgrmelova** [comment]
Dobrý den, 

úprava byla nasazena do produkce. 

Hezký den. 

---
Jana Grmelová
IT administrátor
