### ISSUE TITLE
Nelze použít u transakce tlačítko Reverzal

### ISSUE THREAD

**Issue by pulitricek** [csob/platebnibrana#46]
Dobrý den, nedaří se nám aktivovat platební bránu. Nelze totiž udělat požadovaný reverzal, abychom splnili poslední krok v testu platební brány. Po kliknutí na tlačítko "Reverzal" se objeví hláška "Služba není momentálně k dispozici. Zkuste to prosím později.". Už tam svítí dva dny. Díky za pomoc.

**Comment by mjanek** [comment]
Dobrý den,
Váš požadavekbyl zaevidován a předán k řešení. O dalším průběhu Vás budeinformovat odpovědný servisní technik.
S pozdravem 
Miroslav Janek

**Comment by FVarak** [comment]
Dobrý den,

v tuto chvíli by již měla být reverzal funkce v pořádku.

S pozdravem

Filip Vařák
