### ISSUE TITLE
{"resultCode":110,"resultMessage":"Invalid parameter merchantId A3507FwVD9"}

### ISSUE THREAD

**Issue by AdamHostin** [csob/platebnibrana#48]
Dobrý deň,

pri  volaní payment/init na testovacom prostredí dostáva odpoveď {"resultCode":110,"resultMessage":"Invalid parameter merchantId A3507FwVD9"}.  Mohli by ste mi prosím pomôcť?

httpOptions:
 {"host":"iapi.iplatebnibrana.csob.cz","port":443,"path":"/api/v1.9/payment/init","method":"POST","headers":{"Content-Length":758,"Content-Type":"application/json"},"allowedTryouts":3,"tryoutDelay":20000}

 Payload:{"merchantId":"A3507FwVD9","orderNo":"2424170005","dttm":"20230920153640","payOperation":"oneclickPayment","payMethod":"card","totalAmount":100,"currency":"CZK","closePayment":false,"returnUrl":"https://test.a.rest.taxi.hopintaxi.com:6001/customer/cards/regResponseCSOB?lang=sk","returnMethod":"POST","cart":[{"name":"Svez.se","quantity":1,"amount":100}],"merchantData":"2424170005","language":"cs","signature":"Hot/7NVp8a5XEamIBYCErDzFPWV2HapEbXCRBPhKcJh0znYkg8qnb1+jPOflE4QipLyt7N56OGNaMT0lM0QmCnT9v+qWWBLF2IaYCCU6WObt61Du2GzAfMMUviHo9S0V3ZrnARDCY1wtCj5gvVEvhCWHPlD+14/f1lrps9WeJWtPYHSq+dxCTvGxhCkqwrHIYXQGEvbIqwulNZGSQ042qti4amd6Dmf25J8QhzaxCkc2BZx+AFMtsAWTXt2LbTZDEfPFWIpmriErrCA65ztU5wwpk0FAXcPiA5FOvFy2BzvZmRpKzCYg8sNsCulh7wRjHATdlte/JFeC0Qf5OPZ3dw=="}

**Comment by martinhubik-mp** [comment]
Dobrý den, 

Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

S pozdravem

Martin Hubík
1st level support
M [+420 603 197 054]
(tel:+420603197054)
E [servis@monetplus.cz]
MONET+,a.s., Za Dvorem 505, 763 14 Zlín-Štípa

**Comment by jgrmelova** [comment]
Dobrý den, 

použité Merchant ID A3507FwVD9  v databázi na integračním prostředí nevidím. Anonymní Merchant ID má omezenou platnost. Platnost A3507FwVD9 pravděpodobně expirovala nebo se jedná o chybné Merchant ID. 

Anonymní Merchant ID slouží především pro základní seznámení se. Pro plnohodnotné testování doporučuji si zažádat o testovací Merchant ID, které je následně potřebné i pro provedení testovacího scénáře u přechodu do produkčního prostředí.

V případě dalších dotazů, jsem Vám k dispozici. 

---
S pozdravem

Jana Grmelová
IT administrátor
