### ISSUE TITLE
Nefungují testovací karty

### ISSUE THREAD

**Issue by arnostbolehlav** [csob/platebnibrana#5]
Dobrý den,
pracuji na přechodu na verzi 1.9.
Bohužel žádná z testovacích karet na testovací bráně není vyhodnocena pozitivně.
Nefungují ani, když přepnu provozní web s verzí 1.8 na testovací prostředí.
Vždy obdržím hlášení: 
![image](https://user-images.githubusercontent.com/108409892/176443473-f3874005-c192-4cae-bf45-eec37fcc644d.png)

**Comment by pklucka** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Ing. Petr Klučka
IT Support Specialist

**Comment by jgrmelova** [comment]
Dobrý den, 

můžete mi, prosím, zaslat Merchant ID platební brány? 
Situaci prověřím. 

Děkuji.

---
Jana Grmelová
IT administrátor

**Comment by arnostbolehlav** [comment]
Dobrý den,
pro test používám A2418msYP9.

**Comment by jgrmelova** [comment]
Dobrý den, 

děkuji za informaci. Situaci již prověřujeme. O výsledku Vás budeme informovat. 


--
Jana Grmelová
IT administrátor

**Comment by jgrmelova** [comment]
Dobrý den, 

aktuálně by již mělo být v pořádku. Prosím Vás o otestování i z Vaší strany. 

Děkuji. 

--
Jana Grmelová
IT administrátor

**Comment by janbrasna** [comment]
@jgrmelova Nejspis ne, viz:
- #9

**Comment by jgrmelova** [comment]
Dobrý den, 

jednalo se o dvě různé situace. Kdy v prvním případě docházelo v 3DS2 k zamítnutí transakcí u anonymních obchodníků kvůli chybějícím údajům, které jsou nyní pro 3DS2 povinné.  

V druhém případě došlo k nedostupnosti platební brány na integračním prostředí z technických důvodů - chyba hardware na integračním prostředí a následné nekorektní naběhnutí aplikace pro autentikaci.

Aktuálně je již platební brána na integračním prostředí plně funkční. Požadavek tedy uzavírám. 


V případě potřeby je možné vytvořit požadavek nový nebo tento požadavek  znovu otevřít.

Hezký den.

--
Jana Grmelová

**Comment by arnostbolehlav** [comment]
Dobrý den,
už to funguje. 
Děkuji moc
