### ISSUE TITLE
Duplicitní VS

### ISSUE THREAD

**Issue by kuklas317** [csob/platebnibrana#50]
Dobrý den,
měl bych pár dotazů ohledně VS v testovacím prostředí.
1.) Je možné nějakým způsobem odmazávat vzniklé transakce v posmerchant? 
2.) Je možné nějak dovolit totožné VS pro jeden účet platební brány? Jedná se mi o to, že máme nastavenou pouze sekvenci čísel, kterou chceme využívat a určitě nastane situace, že se nám budou shodovat VS.

Děkuji

**Comment by FVarak** [comment]
Dobrý den,

Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

S pozdravem

1st level support
M [+420 603 197 054]
(tel:+420603197054)
E [[servis@monetplus.cz](mailto:servis@monetplus.cz)]
MONET+,a.s., Za Dvorem 505, 763 14 Zlín-Štípa

**Comment by mrazekl** [comment]
Dobrý den,

ad 1) transakce není možné žádným způsobem vymazat

ad 2) Po domluvě s bankou je možné kontrolu na jedinečnost VS vypnout. Změnu lze domluvit přes kontakty akceptacekaret@csob.cz nebo platebnibrana@csob.cz

**Comment by kuklas317** [comment]
Dobrý den,
a jakým způsobem se řeší situace, že dojde k vyčerpání VS, tedy budeme číslovat znovu od 1 když vytváříme VS inkrementálně? Jde nějak kontrola vyresetovat nebo je časové omezení?

Děkuji

**Comment by mrazekl** [comment]
Dobrý den,
existuje zde časové omezení po dobu 13 měsíců, to odpovídá době, po kterou jsou transakce drženy v historii, oproti které se kontrola provádí. Pokud vám tedy číselná řada vydrží déle než 13 měsíců, nemělo by dojít k překrytí VS.
