### ISSUE TITLE
oneclick/echo response v případě chybového status kódu

### ISSUE THREAD

**Issue by ondrejbenes** [csob/platebnibrana#54]
Dobrý den,

prosím o příklad odpovědi z `oneclick/echo` v případě, že je povolená extension `maskClnRP`, a že šabloně, resp. kartě vypršela expirace (status kódy 710, resp. 720).

Rád bych si ověřil, že i v těchto případech je součástí odpovědi maskované číslo karty.

**Comment by FVarak** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení.
S pozdravem
F. Vařák

**Comment by jgrmelova** [comment]
Dobrý den, 

v případě, že se jedná o produkční prostředí a šablona expirovala, je vrácena informace "Oneclick template payment expired" ("Oneclick template card expired "). Další zpracovaní se přeskakuje. K vrácení extensions tedy v těchto případech nedochází. 

---
S pozdravem 
Jana Grmelová
IT administrátor

**Comment by ondrejbenes** [comment]
OK, děkuji, za mě možno issue zavřít.
