### ISSUE TITLE
Limit na provedení operace

### ISSUE THREAD

**Issue by oto-stefan** [csob/platebnibrana#55]
Při testování na platební bráně jsem narazil při pokusu o vytvoření platby s (nerealisticky) velkou částkou na odpověď s `resultCode` 120 a `resultMessage` "Merchant trx limit exceeded".

Na základě toho se nabízí otázky: 
- Jaká je maximální povolená částka pro zadání platby (kromě CZK mě zajímají také EUR a USD)?
- Je limit stejný pro _klasické_ platby i _platby na míru_?
- Jedná se o univerzální limit nebo je individuální pro každého zákazníka a je dohodnut při sjednání smlouvy?

V dokumentaci jsem odpovědi nenašel, ale nemohu vyloučit, že jsem něco přehlédl.

Předem díky a přeju hezký den.

**Comment by jgrmelova** [comment]
Dobrý den, 

jedná se denní limit všech autorizovaných plateb pro platební bránu obchodníka. Tedy jak pro klasické platby, tak i platby na míru. 
Pokud systém detekuje možnost překročení denního limitu, nedovolí vytvoření další transakce, u které by autorizací došlo k překročení denního limitu. 
 
Bližší informace ohledně denního limitu a jeho výšky, Vám poskytne obchodní zástupce banky. 

Hezký den. 

---
Jana Grmelová
IT administrátor

**Comment by oto-stefan** [comment]
Děkuji za vysvětlení.
