### ISSUE TITLE
Invalid payload v applepay/init

### ISSUE THREAD

**Issue by MMirekk** [csob/platebnibrana#56]
Dobrý den, 
například dnes 11.4.2024 12:21
zkouším poslat applepay/init request. A vrací mi to stále chybu Invalid payload. Pečlivě jsem zkontroloval certifikáty (abych neměl stejnou chybu jako v jiných issues) A raději i vytvořil nový certifikát.
Request posílám na testovací bránu https://iapi.iplatebnibrana.csob.cz/api/v1.9/applepay/init
MerchantID mám: M1MIPS0829
payload zakóduji base64 to co mi vrátí applepay a to je (zkráceně):
{"data":"qIoxR...","signature":"MIA...","header":{"publicKeyHash":"Jzg...","ephemeralPublicKey":"MFk...","transactionId":"..."},"version":"EC_v1"}
obdobně to dělám u googlePay a tam mi vše funguje jak má. Můžete mi prosím na to mrknout a poradit kde je chyba. Už moc nevím kde hledat. Díky moc

**Comment by martinhubik-mp** [comment]
Dobrý den,
Váš požadavek byl zaevidován pod: KBC-11983 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem


Martin Hubík
1st level support
M [+420 603 197 054](tel:+420603197054)E [servis@monetplus.cz](mailto:servis@monetplus.cz)MONET+,a.s., Za Dvorem 505, 763 14 Zlín-Štípa[monetplus.com](http://monetplus.com/) | [linkedin](https://www.linkedin.com/company/monetplus/) | [facebook](https://www.facebook.com/monetplus/) 
Česká republika
[www.monetplus.cz](http://www.monetplus.cz/)

**Comment by jgrmelova** [comment]
Dobrý den, 


dle url adresy, na kterou request zasíláte se jedná o integrační prostředí - _https://**i**api.**i**platebnibrana.csob.cz/api/v1.9/applepay/init_.
V logu jsem dohledala hlášku: Apr 11, 2024 @ 12:21:22.067 skipping processing, **unable to load merchant's applepay processing certificate**


Provedla jsem proto kontrolu certifikátu v systému POS Merchant pro integrační prostředí a certifikát pro Apple Pay na integračním prostředí chybí.  Viz
![image](https://github.com/csob/platebnibrana/assets/100124293/9ce9676c-0232-4b6b-b91f-cac383d0b7bd)


Na produkčním prostředí v systému POS Merchant vidím certifikát vložen dnes 11.04.24. Je tedy možné, že požadavek zasíláte místo na produkční tak na integrační prostředí nebo byl certifikát pro integrační prostředí omylem vložen na produkční prostředí. 


Hezký den. 

---
Jana Grmelová
IT administrátor

**Comment by MMirekk** [comment]
ahaa, tak v tom bude asi ten problém, o posmerchant na testovacím prostředí sem nevěděl, už sem našel že je na https://iposman.iplatebnibrana.csob.cz, ale nevím jak tam vytvořit uživatele, to si mám napsat na akreditace@csob.cz? Díky moc Problém bude určitě v tom, že používám certifikát, který sem nahrál na produkční prostředí. Pravděpodobně vyřeším tím, že se dostanu a nahraju na integrační posmerchant.

**Comment by jgrmelova** [comment]
Dobrý den, 

o přístupové údaje do systému POS Merchant můžete požádat obchodního zástupce nebo poslat žádat na uvedený e-mail akceptacekaret@csob.cz. 

V případě doplňujících dotazů, jsem Vám k dispozici. 

---
Jana Grmelová
IT administrátor

**Comment by MMirekk** [comment]
Díky, přístup už mám, potvrzuji, že applepay/init už mi funguje, díky za pomoc a můžete tuhle issue uzavřít, díky moc

**Comment by jgrmelova** [comment]
Dobrý den, 

rádo se stalo. 

Hezký den. 

---
Jana Grmelová
IT administrátor
