### ISSUE TITLE
Po změně privátního klíče vrací testovací rozhraní Bad request

### ISSUE THREAD

**Issue by kuklas317** [csob/platebnibrana#57]
Dobrý den,
před nějakou dobou nám byl změněn privátní klíč pro komunikaci s testovací platební bránou. V rámci testovacího prostředí jsme tedy klíč nahradili a zkusili provolat rozhraní. Bohužel, rozhraní nám pořád vrací Bad Request a nepodařilo se nám zjistit z jakého důvodu. Podle logu se to děje při každém volání. Dnes 18.4. cca ve 13:30 jsem zase zkusil provolat rozhraní  a pořád bez změny.  Provoláváme rozhrani https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/init a používáme merchant id M1MIPS5805. 

Mohu vás poprosit o prověření z jakého důvodu init request je odmítnán? V rámci aplikace nebyla provedena změna, jediné co bylo změněno je privátní klíč a případně úpravy jiných částí aplikace nesouvisejicích s platební bránou.

Děkuji

**Comment by DanielKubicek** [comment]
Dobrý den,
tento požadavek byl zaevidován pod KBC-12196 a předán k řešení.

**Comment by kuklas317** [comment]
Dobrý den,
děkuji za informace. Komunikace se nám podařila zprovoznit.
