### ISSUE TITLE
v1.9 endpoint data  

### ISSUE THREAD

**Issue by OndrejSykora** [csob/platebnibrana#6]
Zdravím,

na testovacím prostředí mám drobný nesoulad s tím co je v dokumentaci a co chodí z API. Po odeslání požadavku na endpoint **oneclick/init**  se vrátí odpověď s následující strukturou...

```
{
    "payId": "43e65b2f79b3@HG",
    "resultCode": 0,
    "resultMessage": "OK",
    "paymentStatus": 1,
    "dttm": "20220706102407",
    "signature": "base64-encoded-request-signature",
    "actions": {
        "fingerprint": {
            "browserInit": {
                "url": "https://iplatebnibrana.csob.cz/pay/mall.cz/b8296189-a8b6-4e48-a210-6170e5a3db79/3ds/method",
                "method": "GET",
                "params": {}
            }
        }
    }
}
```

Ale podle dokumentace by měl být v objektu **browserInit** místo parametru **params** být parametr **vars** viz  https://github.com/csob/platebnibrana/wiki/Metody-pro-OneClick-platbu#endpoint

**Comment by janbrasna** [comment]
Ono by hlavne podle dokumentace jak default `method` tak prazdne `vars` vubec nemely byt nikdy posilany :( — resp. pro GET nikdy ani nebudou `vars` pritomne, ale cely querystring je uz primo v `url`…

A protoze aktualne zadna operace neintegruje POST metody, tak nikdy zadny endpoint nebude obsahovat nic vic nez jen sve `url` ~ tj. tohle musi nekdo opravit, to tam nema co delat.

(Ale nez to opravi, tak si musi fixnout i spatne pojmenovany klic, dobry postreh! Diky!)

**Comment by jgrmelova** [comment]
Dobrý den, 

požadavek jsem předala na vývojáře. O dalším průběhu Vás budeme informovat.

Hezký den. 

---
Jana Grmelová
IT administrátor

**Comment by dmarek** [comment]
Dnes 19.7. byla oprava nasazena na produkčním prostředí.

**Comment by jgrmelova** [comment]
Dobrý den, 

oprava byla nasazena na produkční prostředí 19.07.22. Tento požadavek v tuto chvíli tedy uzavírám. 

V případě potřeby je možné vytvořit požadavek nový nebo tento požadavek znovu otevřít.

Hezký den.

--
Jana Grmelová
