### ISSUE TITLE
Náhodně zamítnutá platba - po požadované úpravě ohledně údajů kupujícího

### ISSUE THREAD

**Issue by MilanVilim** [csob/platebnibrana#62]
Dobrý den,
na základě vašeho požadavku jsem začali do 3DSecure procesu posílat e-mailovou adresu, kterou nám kupující sděluje. Tuto úpravu aktuálně máme nasazenou na testovacím prostředí.

Bohužel od té doby se nám stává, že při platbě NaKlik v nativních aplikacích (3DS SDK NetCetera – v nativkách používáme již tu novou verzi 2.4.1.2) dostaneme zamítnutí platby. K zamítnutí dojde ještě před otevřením dialogu, kde by měl uživatel zadat kód pro ověření (1234).

Neumíme toto nějak jednoznačně navodit, obvykle to projde(opakované platby jednou uloženou kartou), ale někdy ne. Níže je výčet posledních plateb, kdy to nastalo. Ten stejný košík lze zaplatit standardní platbou. Další koších zaplatím tou stejnou uloženou kartou (jinou novou kartu po chybě neukládám).

Prosím, můžete ověřit/zjistit, proč došlo u těchto plateb k zamítnutí platby (Status platby 6)?
[Zamítnutá platba ff4f6a842c0e@JG.txt](https://github.com/user-attachments/files/16126324/Zamitnuta.platba.ff4f6a842c0e%40JG.txt)

Odmítnuté platby:
ff4f6a842c0e@JG - iOS zařízení (v příloze výpis z komunikace s eAPI – některá data jsou vynechána)
149f4e0eea31@JG - iOS zařízení
c729aa2d2cea@JG - iOS zařízení
13e15f8d9d10@JG - iOS zařízení
759023743a71@JG – Android zařízení
30a9fb92cef0@JG – Android zařízení

**Comment by martinhubik-mp** [comment]
Dobrý den,
Váš požadavek byl zaevidován pod: KBC-13685 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Martin Hubík
1st level support
M [+420 603 197 054](tel:+420603197054)E [servis@monetplus.cz](mailto:servis@monetplus.cz)MONET+,a.s., Za Dvorem 505, 763 14 Zlín-Štípa[monetplus.com](http://monetplus.com/) | [linkedin](https://www.linkedin.com/company/monetplus/) | [facebook](https://www.facebook.com/monetplus/) 
Česká republika
[www.monetplus.cz](http://www.monetplus.cz/)

**Comment by jgrmelova** [comment]
Dobrý den, 

prověřila jsem několik zaslaných transakcí. U těchto transakcí vidím, že je vyplněna částka 200.00. Viz

ff4f6a842c0e@JG ->200.00
149f4e0eea31@JG ->200.00
c729aa2d2cea@JG ->200.00

Na integračním prostředí se pro nasimulování a otestování různých situací pro metodu OneClick využívají různé částky.
Např. 200 / 20000 = Simulace **neúspěšného ověření** (bez nutnosti provádět potvrzení platby zákazníkem). Pro danou kartu je vyžadováno provedení otisku prohlížeče. Nepokračuje se do autorizace, **platba je zamítnuta.**
 
Další možnosti můžete vidět zde: https://github.com/csob/platebnibrana/wiki/Testovac%C3%AD-karty

V případě doplňujících dotazů, jsem Vám k dispozici. 

Hezký den. 

---
Jana Grmelová

**Comment by MilanVilim** [comment]
Díky, jasně to znám. Ty částky jsem si při nákupu jízdenek vůbec neuvědomoval.
