### ISSUE TITLE
{"resultCode":110,"resultMessage":"Wrong signature"}

### ISSUE THREAD

**Issue by JaHa0** [csob/platebnibrana#65]
Prosím o analýzu, proč platební brána neakceptuje podpis. Viz screenshot odesílané zprávy.. (generované 30.07.2024, 22:58)

**Comment by JaHa0** [comment]
poznámka: problém nastal po implementaci atributu "customer" do kterého nově vkládáme jméno + email

**Comment by martinhubik-mp** [comment]
Dobrý den,
Váš požadavek byl zaevidován pod: KBC-14078 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Martin Hubík
1st level support
M [+420 603 197 054](tel:+420603197054)E [servis@monetplus.cz](mailto:servis@monetplus.cz)MONET+,a.s., Za Dvorem 505, 763 14 Zlín-Štípa[monetplus.com](http://monetplus.com/) | [linkedin](https://www.linkedin.com/company/monetplus/) | [facebook](https://www.facebook.com/monetplus/) 
Česká republika
[www.monetplus.cz](http://www.monetplus.cz/)

**Comment by JaHa0** [comment]
Problém vyřešen. Omylem byla zpráva zašifrována ještě starou šifrou.. po změně na SHA256 už to funguje,

$res = openssl_verify ( $text, $signature, $publicKeyId, OPENSSL_ALGO_SHA256);

**Comment by JaHa0** [comment]
Dobrý den,

problém jsme již vyřešili, viz vlákno na githubu.

 

Děkuji

 

S pozdravem

 

Jan Haubner
