### ISSUE TITLE
Testovací API nepřijímá Merchant ID v metodě ECHO

### ISSUE THREAD

**Issue by drosena3** [csob/platebnibrana#68]
Dobrý den,
vyvíjíme napojení e-shopu na eAPI platební bránu ČSOB. Při vývoji jsme narazili na překážku a to, že testovací API  https://iapi.iplatebnibrana.csob.cz/api/v1.9/ nepřijímá MERCHANT ID vygenerovaný keygenem na adrese https://iplatebnibrana.csob.cz/keygen/ - kde jsme si mimo jiné vygenerovali privátní a veřejný klíč.

Pro kontrolu odpovědi při vývoji, jsme využili metodu echo. Posílali jsme hodnoty (payload) {'merchantId': 'A5148FMMeC', 'dttm': '20240814092238', 'signature': 'Qq384h9caSM/KbvOpFIwMITuTUt1yBp5uXKWNg3gm+cPkQqmux4fJLaCu+bKoPMvRzi3EDxr4//xRNFOOzFKwRQPU4HPucXKMolo/kxM79tJXuWUQ27kfaboWBl3nBoOAAdWajeuDx8MUaXUKJ/Y1YPT760QvRWh7LXVoyga0s4Cl+SY9iIKzCb6lqpSH07ZLAj7E3g09I6IsiS4VDmBNy/ZDs4fPU+fTToYmt9HiBVR77VPskeWododw5rbz/CYjrFfMmVwDzHjZh5IXmkeLCdPreKm4/k1AtOfaqFeaR8B3qGtR6uKYBXVUuuvi62RcrcMqNt0/nulW/4OvMUi8w=='} na tuto testovací url https://iapi.iplatebnibrana.csob.cz/api/v1.9/echo a dostali jsme následujcí výstup: Code:900 Invalid request: merchant key not found for A5148FMMeC. V příloze naleznete vygenerový privátní klíč, veřejný klíč a Merchant id a bloky logů (zkoušeno na api v1.9, api v1.8, a bez specifikace api) s chybovými hláškami.

Mohli bychom od Vás poprosit o zpětnou vazbu, zda posíláme data správným způsobem a či nevidíte důvod proč operace neproběhla korektně?

Děkuji
[echo_metoda_loggy.txt](https://github.com/user-attachments/files/16651901/echo_metoda_loggy.txt)
[merchant_id_privatekey_publickey.txt](https://github.com/user-attachments/files/16651902/merchant_id_privatekey_publickey.txt)

**Comment by jgrmelova** [comment]
Dobrý den, 

"Merchant key not found for merchantId A5148FMMeC" znamená, že na straně banky chybí veřejný klíč obchodníka. Ten se v případě generování anonymního Merchant ID zašle po vygenerování kliknutím na tlačítko "Odeslat veřejný klíč do banky". 

Pro implementaci bych doporučila požádat o vytvoření plnohodnotného Merchant ID pro integrační prostředí. A to z důvodu, že anonymní Merchant ID nepodporuje všechny platební metody, má omezenou platnost a slouží spíše pro prvotní náhled. 

V případě jakýchkoliv dotazů, jsme Vám k dispozici. 

Hezký den. 

---
Jana Grmelová
IT administrátor

**Comment by drosena3** [comment]
Dobrý den,
děkuju vyřešeno.
