### ISSUE TITLE
Podlimitní platby oneclick - Kdo řeší limit 700,-

### ISSUE THREAD

**Issue by MilanVilim** [csob/platebnibrana#70]
Kdy mám zvolit v operaci oneclick/init parametr payMethod na card#LVP s ohledem na limit podlimitní platby (částka menší než 700)? 

Jde mi o to, jestli mám na naší straně zkontrolovat, zda je částka nižší než 700 a pak můžu tento parametr zapnout nebo parametr zapnu vždy a platební brána rozhodne, zda je skutečně o podlimitní platbu.

Jde vlastně i to, že máme platby v Eurech. Tam musím limit přepočítávat podle stanoveného kurzu.

**Comment by jgrmelova** [comment]
Dobrý den, 

pokud si přejete využívat výjimku ze silného ověření pro podlimitní transakce, je nutné nejprve požádat akceptacekaret@csob.cz o aktivaci. Služba není aktivní automaticky. 
Detailní informace viz https://github.com/csob/platebnibrana/wiki/Ov%C4%9B%C5%99en%C3%AD-karetn%C3%ADch-plateb#v%C3%BDjimka-ze-siln%C3%A9ho-ov%C4%9B%C5%99en%C3%AD-pro-podlimitn%C3%AD-transakce-

Následně je na Vašem zvážení, u kterých transakcí budete v rámci inicializace žádat o výjimku ze silného ověření LVP. 
Pokud však zažádáte o LVP u transakce, která překračuje limit, tak se výjimka neaplikuje. Výjimka se aplikuje pouze v případě, že je částka nižší než stanovený limit. Detaily viz odkaz výše. 

V případě doplňujících dotazů, jsem Vám k dispozici. 

Hezký den. 

---
Jana Grmelová

**Comment by MilanVilim** [comment]
Děkuji za informaci. Rozumím.
