### ISSUE TITLE
Při testování na testovacím prostředí brána stále požaduje 3DS fingerprint a následně challenge. Je LVP povoleno?

### ISSUE THREAD

**Issue by AlesCrkva** [csob/platebnibrana#71]
Níže výpis komunikace vč. payId transakce pro kontrolu u banky.

2024-09-29 20:57:30  10.0.0.2        URL to send request to: https://iapi.iplatebnibrana.csob.cz/api/v1.9/oneclick/init
2024-09-29 20:57:30  10.0.0.2        JSON payload:
{
    "merchantId": "M1MIPS4044",
    "origPayId": "21b23b018b15@JI",
    "orderNo": "46384",
    "dttm": "20240929205730",
    "payMethod": "card#LVP",
    "clientIp": "10.0.0.2",
    "totalAmount": 3000,
    "currency": "CZK",
    "closePayment": true,
    "returnUrl": "pid-litacka-prerelease://order/46384",
    "returnMethod": "GET",
    "clientInitiated": true,
    "sdkUsed": true,
    "merchantData": "",
    "signature": "dUtBer7iGSb93ieJffgqlPSRepW87HxXMyTzU4VVjMfWOFhTUliy+8cMWmJwzzcj42M0gynH+WSv1G3Dnu1sZBZRz8IVbtJQUB+gOcfBenXFlO1RHSaQ95r0KIvKhhssRRwdvbznc3c9SToj1vJTNdZCalLVEVXBiwu2jGpCQxTKwZaGdYbTL
aQCM6esNmBATqORU1UoYfyT7Svvy+DPQP+DR3v1myBUoH8mq44r8kBCVAzPSaQtHGTotg7sMeO9w/1edbq/z2FbQKlsuT3TNNsskkOQDJqPZ7P4K2L+fZ44yoZDt+5n8ra7fowfyeg0g/xA743+vVR61CN78MrNNg=="
}
2024-09-29 20:57:30  10.0.0.2        API response:
{
    "payId": "cf4e29733357@JI",
    "resultCode": 0,
    "resultMessage": "OK",
    "paymentStatus": 1,
    "dttm": "20240929205730",
    "signature": "bJ41mx0VHyvV3wAf5/ElQD8YhxhQ5vGSpr34qI7LRnwOavcR43/hCecXSygF1HUCIlr4VVZfkLJ4ovE8o73LxJ5c7SebcnNqZu0EVXJsvDark0qMpJ1GlIYRZz2NfzxEhDA4Cb8tdiTwEyqc6OFOJYPpQF38qbr6JfXxmQ4L8NfQLmTj0pGOZ
kkRo9dtsgRU9Jo0eBv5nWTuI1pZ/HlTnNgq+MeVbeY2pKKvt8HWx3oHilFX3LSuHBFEJ4vYEuUP8X71vxzx0EWAi0xJ1t/Hj5YmUhwywxSh4t5RHxYKqdMAA8mp8TjCm2CyCzPTfZI42uqI5147crl/VNioEW850Q==",
    "actions": {
        "fingerprint": {
            "sdkInit": {
                "directoryServerID": "A000000003",
                "schemeId": "Visa",
                "messageVersion": "2.2.0"
            }
        }
    }
}

**Comment by jgrmelova** [comment]
Dobrý den, 

pro Merchant ID M1MIPS4044 nejsou LVP na integračním prostředí povoleny. LVP jsou povoleny pouze u produkčního prostředí. Pro povolení i na integračním prostředí kontaktujte akceptacekaret@csob.cz.  

---
Jana Grmelová
IT administrátor

**Comment by AlesCrkva** [comment]
Dobrý den, 

tak jak mi vysvětlíte tento e-mail?

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/e03e15ea-ddb1-4c0c-82fb-66d5a96cd8cd">

**Comment by jgrmelova** [comment]
Vyřešeno e-mailovou komunikací.
