### ISSUE TITLE
Dotaz k chybě 710: Oneclick template payment expired

### ISSUE THREAD

**Issue by paveldedik** [csob/platebnibrana#74]
Dobrý den,

ve Skip Pay se nám občas objevují chyby `710` při volání endpointu `onclick/init`. Určitě je vyloučeno, že by došlo k chybě kvůli expiraci po 12 měsících, jak je zmíněno v dokumentaci:

> 710: **Oneclick template payment expired** (OneClick the template has not been used for more than 12 months, the payment has expired)

Tedy otázkou je, proč se tato chyba objevuje. Je možné, že každý request na `oneclick/init` vrací nové `payId` a staré se invaliduje? Toto není nikde v dokumentaci explicitně zmíněno.

Pokud nové `payId` invaliduje staré, je možné mít více šablon pro one click payment?

**Comment by martinhubik-mp** [comment]
Dobrý den,
Váš požadavek byl zaevidován pod: KBC-15816 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Martin Hubík
1st level support
MONET+,a.s., Za Dvorem 505, 763

**Comment by jgrmelova** [comment]
Dobrý den, 

můžete nám, prosím, zaslat ID platební brány a ideálně konkrétní příklad, kde se domníváte, že došlo k chybné odpovědi? 

Bližší informace můžete případně zaslat na e-mail servis@monetplus.cz. 

Situaci prověříme.  

---
S pozdravem

Jana Grmelová

**Comment by paveldedik** [comment]
Dobrý den,

děkuji za rychlou reakci, poslal jsem email s předmětem "Dotaz na GitHubu #74"

**Comment by paveldedik** [comment]
Vyřešeno po mailu.
