### ISSUE TITLE
v1.9 googlepay/echo špatný název parametru

### ISSUE THREAD

**Issue by Daaarkling** [csob/platebnibrana#8]
Ahoj,

při requestu na `googlepay/echo` dostávám odpověď: 

```
'resultCode' => 0
'resultMessage' => 'OK'
'dttm' => '20220707080942'
'initParams' => array...
```

Podle dokumentace by se ale parametr měl jmenovat `checkoutParams` ne `initParams`, ten je pro apple pay.

**Comment by janbrasna** [comment]
Je to chyba dokumentace, tak se ten param jmenoval kdysi… Divam se do schematu a dneska je stejny s Pay tj. to co vraci aplikace je spravne.

Dokumentace potrebuje opravit.

**Comment by jgrmelova** [comment]
Dobrý den, 

požadavek na úpravu dokumentace jsem předala na vývojáře. 

Hezký den. 

---
Jana Grmelová
IT administrátor

**Comment by Daaarkling** [comment]
Ještě mám jeden problém a sice ověření podpisu při tomto volání `googlepay/echo`. V response se mi správně vrátí data: 
```
'resultCode' => 0
'resultMessage' => 'OK'
'dttm' => '20220708085734'
'initParams' => array
    'apiVersion' => 2
    'apiVersionMinor' => 0
    'paymentMethodType' => 'CARD'
    'allowedCardNetworks' => array
        0 => 'VISA'
        1 => 'MASTERCARD'
    'allowedCardAuthMethods' => array
        0 => 'PAN_ONLY'
        1 => 'CRYPTOGRAM_3DS'
    'assuranceDetailsRequired' => false
    'billingAddressRequired' => false
    'billingAddressParametersFormat' => 'FULL'
    'tokenizationSpecificationType' => 'PAYMENT_GATEWAY'
    'gateway' => 'csob'
    'gatewayMerchantId' => 'abc'
    'googlepayMerchantId' => 'xyz'
    'merchantName' => 'Slevomat.cz'
    'environment' => 'TEST'
    'totalPriceStatus' => 'FINAL'
    'countryCode' => 'CZ'
```

Ze kterých vygeneruju řetězec: ```
20220708085734|0|OK|2|0|CARD|VISA|MASTERCARD|PAN_ONLY|CRYPTOGRAM_3DS|false|false|FULL|PAYMENT_GATEWAY|csob|abc|xyz|Slevomat.cz|TEST|FINAL|CZ
```

Při ověřování podpisu to ale selže. U všech ostatních requestů ověřování funguje. Nemůže být chyba v dokumentaci v pořadí argumentů?

**Comment by jgrmelova** [comment]
Dobrý den, 

název parametru jsme v dokumentaci opravili. Co se týče ověření podpisu při volání googlepay/echo prověříme a budeme Vás informovat. 

Hezký den. 

--- 
Jana Grmelová
IT administrátor

**Comment by janlanger** [comment]
@jgrmelova Dobrý den, máte k problému prosím nějaké nové informace?

**Comment by janbrasna** [comment]
@jgrmelova Related:
- https://github.com/csob/paymentgateway/issues/634

tzn. jak se ma spravne nakladat s podpisem _arrays_, muze souviset… ⬆️

**Comment by janlanger** [comment]
No máme Google Pay funkční na eApi 1.8 kde je ta struktura stejná, takže v tom to asi nebude, leda by se verzí něco změnilo..

**Comment by dmarek** [comment]
Dnes 19.7. byla oprava nasazena na produkčním prostředí.

**Comment by Daaarkling** [comment]
Děkuji a potvrzuji funkčnost. 

Bohužel se ale objevil jiný problém https://github.com/csob/platebnibrana/issues/11

**Comment by jgrmelova** [comment]
Dobrý den, 

děkuji za informaci. Tento task uzavírám. 
Dalšímu požadavku se budeme věnovat v rámci tasku #11. 

--
Jana Grmelová
