### ISSUE TITLE
Problém s sandbox čsob - platba kartou

### ISSUE THREAD

**Issue by KDKftw** [csob/platebnibrana#9]
Dobrý den,
Máme verzi 1.8 api a nefunguje nám platba testovací kartou 4000007000010006 kterou beru z vašeho githubu. Platba neprojde. Vyskočí mi následující hláška:
 
![csob_sandbox_err](https://user-images.githubusercontent.com/60475700/179740554-73e22a15-dc13-4cbe-9813-512e7e0b0d57.png)

merchantId="M1MIPS6007"
Transaction ID / PAYID je : a94ca234f901@HG

Můžete mi prosím poradit či prověřit proč to nejde? Potřebujeme nutně otestovat novou funkcionalitu po platbě.

Díky moc, 
Ondřej Kadoun

**Comment by jgrmelova** [comment]
Dobrý den, 

Váš požadavek prověřujeme o výsledku Vás budu informovat. 

Hezký den. 

--
Jana Grmelová 
IT administrátor

**Comment by mrazekl** [comment]
Dobrý den,

opraveno. Důvodem byla chyba hardware na integračním prostředí a následné nekorektní naběhnutí aplikace pro autentikaci.

**Comment by jgrmelova** [comment]
Dobrý den,

platební brána na integračním prostředí je již plně funkční. Tento požadavek uzavírám. 

V případě potřeby je možné vytvořit task nový nebo tento task znovu otevřít. 

Hezký den. 

--
Jana Grmelová
